{{- define "mq-webconsole.fullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 52 | trimSuffix "-" -}}
{{- else -}}
{{- default .Release.Name .Values.nameOverride | trunc 52 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}

{{- define "mq-webconsole.labels" -}}
helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" }}
app.kubernetes.io/name: mq-webconsole
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/component: web-console
{{- end -}}

{{/* ----------------------------------------------------------------------- */}}
{{/* mqwebuser.xml — console authn + role mappings                            */}}
{{/* ----------------------------------------------------------------------- */}}
{{- define "mq-webconsole.mqwebuser.xml" -}}
{{- $ldap := eq .Values.registry "ldap" -}}
<?xml version="1.0" encoding="UTF-8"?>
<server>
  <featureManager>
    <feature>appSecurity-2.0</feature>
{{- if $ldap }}
    <feature>ldapRegistry-3.0</feature>
{{- end }}
    <feature>basicAuthenticationMQ-1.0</feature>
  </featureManager>
{{- if $ldap }}
  <ldapRegistry id="ldap" realm="defaultRealm"
    host="{{ .Values.ldap.host }}" port="{{ .Values.ldap.port }}" sslEnabled="{{ .Values.ldap.sslEnabled }}"
    ldapType="Microsoft Active Directory"
    baseDN="{{ .Values.ldap.baseDN }}"
    bindDN="{{ .Values.ldap.bindDN }}"
    bindPassword="{{ .Values.ldap.bindPasswordEncoded }}"/>
{{- else }}
  <basicRegistry id="basic" realm="defaultRealm">
{{- range .Values.basicUsers }}
    <user name="{{ .name }}" password="{{ .passwordEncoded }}"/>
{{- end }}
  </basicRegistry>
{{- end }}
  <enterpriseApplication id="com.ibm.mq.console">
    <application-bnd>
      <security-role name="MQWebAdmin">
{{- if $ldap }}{{- range .Values.consoleRoles.admin }}
        <group name="{{ . }}" realm="defaultRealm"/>
{{- end }}{{- else }}{{- range .Values.basicUsers }}{{ if eq .role "admin" }}
        <user name="{{ .name }}" realm="defaultRealm"/>
{{- end }}{{ end }}{{- end }}
      </security-role>
      <security-role name="MQWebAdminRO">
{{- if $ldap }}{{- range .Values.consoleRoles.adminReadOnly }}
        <group name="{{ . }}" realm="defaultRealm"/>
{{- end }}{{- else }}{{- range .Values.basicUsers }}{{ if eq .role "adminReadOnly" }}
        <user name="{{ .name }}" realm="defaultRealm"/>
{{- end }}{{ end }}{{- end }}
      </security-role>
      <security-role name="MQWebUser">
{{- if $ldap }}{{- range .Values.consoleRoles.user }}
        <group name="{{ . }}" realm="defaultRealm"/>
{{- end }}{{- else }}{{- range .Values.basicUsers }}{{ if eq .role "user" }}
        <user name="{{ .name }}" realm="defaultRealm"/>
{{- end }}{{ end }}{{- end }}
      </security-role>
    </application-bnd>
  </enterpriseApplication>
</server>
{{- end -}}

{{/* ----------------------------------------------------------------------- */}}
{{/* federation.sh — adds remote QMs to this console (the common UI)          */}}
{{/* ----------------------------------------------------------------------- */}}
{{- define "mq-webconsole.federation.sh" -}}
#!/bin/bash
# Generated by mq-webconsole. Adds remote queue managers to THIS console so it
# shows the whole estate. Run once on the ACTIVE pod (or wire into your pipeline):
#   REMOTE_MQ_PW=*** oc exec <pod> -- bash -c 'REMOTE_MQ_PW=$REMOTE_MQ_PW bash /etc/mqm/federation/federation.sh'
set -euo pipefail
: "${REMOTE_MQ_PW:?Set REMOTE_MQ_PW to the federated service-account password}"
KS="{{ .Values.federation.keystorePath }}"
KS_PW="${MQ_KEYSTORE_PW:-}"
{{- range .Values.federation.remoteQueueManagers }}

echo ">> Federating {{ .qmgrName }} ({{ .uniqueName }})"
setmqweb remote add \
  -qmgrName "{{ .qmgrName }}" \
  -uniqueName "{{ .uniqueName }}" \
  -channelName "{{ .channel }}" \
  -connectionName "{{ .connectionName }}" \
  -username "{{ .username }}" -password "${REMOTE_MQ_PW}" \
  -keyStorePath "${KS}" -keyStorePassword "${KS_PW}"
{{- end }}

echo ">> Current federated connections:"
dspmqweb remote
{{- end -}}
