{{/* ----------------------------------------------------------------------- */}}
{{/* Naming + labels                                                          */}}
{{/* ----------------------------------------------------------------------- */}}
{{- define "mqqmgr.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 52 | trimSuffix "-" -}}
{{- end -}}

{{- define "mqqmgr.fullname" -}}
{{- default .Release.Name .Values.fullnameOverride | trunc 52 | trimSuffix "-" -}}
{{- end -}}

{{/* ConfigMap-name prefix for console artifacts produced by the subchart.
     Calls the subchart's fullname with the subchart value context so the names
     always match, even if mq-webconsole.nameOverride is set. */}}
{{- define "mqqmgr.consolePrefix" -}}
{{- include "mq-webconsole.fullname" (dict "Release" .Release "Values" (index .Values "mq-webconsole")) -}}
{{- end -}}

{{- define "mqqmgr.labels" -}}
helm.sh/chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" }}
app.kubernetes.io/name: {{ include "mqqmgr.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/component: queue-manager
{{- end -}}

{{/* ----------------------------------------------------------------------- */}}
{{/* qm.ini — certificate mode only: allow "unknown" (external) users          */}}
{{/* ----------------------------------------------------------------------- */}}
{{- define "mqqmgr.qmini" -}}
Service:
    Name=AuthorizationService
    EntryPoints=14
    SecurityPolicy=UserExternal
{{- end -}}

{{/* ----------------------------------------------------------------------- */}}
{{/* MQSC: CONNAUTH                                                            */}}
{{/* ----------------------------------------------------------------------- */}}
{{- define "mqqmgr.mqsc.connauth" -}}
{{- if eq .Values.clientAuth "certificate" }}
* === Certificate-only: disable password / connection authentication ===
ALTER QMGR CONNAUTH(' ')
REFRESH SECURITY
{{- else if .Values.connAuth.enabled }}
* === Connection authentication (LDAP) — generated by Helm ===
DEFINE AUTHINFO('USE.LDAP') AUTHTYPE(IDPWLDAP) +
   CONNAME('{{ .Values.ldap.host }}({{ .Values.ldap.port }})') SECCOMM({{ ternary "YES" "NO" .Values.ldap.sslEnabled }}) +
   LDAPUSER('{{ .Values.ldap.bindDN }}') LDAPPWD('{{ .Values.connAuth.bindPasswordPlain }}') +
   SHORTUSR('{{ .Values.ldap.shortUser | default "sAMAccountName" }}') +
   BASEDNU('{{ .Values.ldap.baseDN }}') +
   AUTHORMD(SEARCHGRP) BASEDNG('{{ .Values.ldap.baseDN }}') +
   CHCKCLNT({{ .Values.connAuth.checkClient | default "REQUIRED" }}) ADOPTCTX({{ ternary "YES" "NO" .Values.connAuth.adoptContext }}) REPLACE
ALTER QMGR CONNAUTH('USE.LDAP')
REFRESH SECURITY TYPE(CONNAUTH)
{{- end }}
{{- end -}}

{{/* ----------------------------------------------------------------------- */}}
{{/* MQSC: SVRCONN channels                                                   */}}
{{/* ----------------------------------------------------------------------- */}}
{{- define "mqqmgr.mqsc.channels" -}}
* === Server-connection channels — generated by Helm ===
{{- $cipher := .Values.channels.tls.cipher | default "ANY_TLS12_OR_HIGHER" }}
{{- $sslcauth := ternary "REQUIRED" "OPTIONAL" .Values.tls.enabled }}
{{- range .Values.channels.serverConnection }}
DEFINE CHANNEL('{{ .name }}') CHLTYPE(SVRCONN) SSLCAUTH({{ $sslcauth }}) SSLCIPH('{{ $cipher }}') REPLACE
{{- end }}
{{- end -}}

{{/* ----------------------------------------------------------------------- */}}
{{/* MQSC: CHLAUTH                                                             */}}
{{/* ----------------------------------------------------------------------- */}}
{{- define "mqqmgr.chlauth.one" -}}
{{- $t := .t -}}
{{- $issuer := .issuer | default "" -}}
{{- if $t.sslPeer -}}
{{- $chan := $t.channel | default "MQ.ADMIN.SVRCONN" -}}
{{- $certi := ternary (printf " SSLCERTI('%s')" $issuer) "" (ne $issuer "") -}}
{{- if eq ($t.access | default "none") "none" }}
SET CHLAUTH('{{ $chan }}') TYPE(SSLPEERMAP) SSLPEER('{{ $t.sslPeer }}'){{ $certi }} USERSRC(NOACCESS) ACTION(REPLACE)
{{- else }}
SET CHLAUTH('{{ $chan }}') TYPE(SSLPEERMAP) SSLPEER('{{ $t.sslPeer }}'){{ $certi }} USERSRC(MAP) MCAUSER('{{ $t.mcUser | default $t.group }}') ACTION(REPLACE)
{{- end -}}
{{- end -}}
{{- end -}}

{{- define "mqqmgr.mqsc.chlauth" -}}
* === Channel authentication (CHLAUTH) — generated by Helm ===
* Applies to client + federated connections (not the local console bindings path).
{{- if eq .Values.clientAuth "certificate" }}
* Back-stop: deny any certificate not explicitly mapped below.
{{- range .Values.channels.serverConnection }}
SET CHLAUTH('{{ .name }}') TYPE(SSLPEERMAP) SSLPEER('CN=*') USERSRC(NOACCESS) ACTION(REPLACE)
{{- end }}
{{- end }}
{{- range .Values.access.platformTeams }}
{{- include "mqqmgr.chlauth.one" (dict "t" . "issuer" $.Values.tls.caIssuerDN) }}
{{- end }}
{{- range .Values.access.teams }}
{{- include "mqqmgr.chlauth.one" (dict "t" . "issuer" $.Values.tls.caIssuerDN) }}
{{- end }}
{{- end -}}

{{/* ----------------------------------------------------------------------- */}}
{{/* MQSC: APPLY_MQSC service — watches dynamic.mqsc and applies it live      */}}
{{/* ----------------------------------------------------------------------- */}}
{{- define "mqqmgr.mqsc.dynamicservice" -}}
* === Dynamic-queue watcher: applies dynamic.mqsc live without pod restart ===
DEFINE SERVICE(APPLY_MQSC) CONTROL(QMGR) SERVTYPE(SERVER) +
  STARTCMD('/mq-config/start-mqsc.sh') STARTARG({{ .Values.queueManager.name }}) +
  STOPCMD('/mq-config/stop-mqsc.sh') STOPARG('') +
  STDOUT('') STDERR('') REPLACE
{{- end -}}

{{/* ----------------------------------------------------------------------- */}}
{{/* MQSC: AUTHREC (OAM)                                                       */}}
{{/* ----------------------------------------------------------------------- */}}
{{- define "mqqmgr.authrec.one" -}}
{{- $t := .t -}}
{{- $subj := .subj -}}
{{- $id := .id -}}
{{- $prefix := $t.queuePrefix | default "**" -}}
{{- if eq $t.access "readonly" }}
SET AUTHREC OBJTYPE(QMGR) {{ $subj }}('{{ $id }}') AUTHADD(CONNECT,INQ,DSP)
SET AUTHREC PROFILE('{{ $prefix }}') OBJTYPE(QUEUE) {{ $subj }}('{{ $id }}') AUTHADD(BROWSE,INQ,DSP)
SET AUTHREC PROFILE('{{ $prefix }}') OBJTYPE(TOPIC) {{ $subj }}('{{ $id }}') AUTHADD(INQ,DSP)
{{- else if eq $t.access "readwrite" }}
SET AUTHREC OBJTYPE(QMGR) {{ $subj }}('{{ $id }}') AUTHADD(CONNECT,INQ,DSP,SET)
SET AUTHREC PROFILE('{{ $prefix }}') OBJTYPE(QUEUE) {{ $subj }}('{{ $id }}') AUTHADD(ALLMQI,ALLADM,CRT,CLR,PASSALL)
SET AUTHREC PROFILE('{{ $prefix }}') OBJTYPE(TOPIC) {{ $subj }}('{{ $id }}') AUTHADD(ALLMQI,ALLADM,CRT)
{{- else }}
* {{ $id }}: access={{ $t.access | default "none" }} -> no authority granted (default deny)
{{- end -}}
{{- end -}}

{{- define "mqqmgr.mqsc.authrec" -}}
{{- $cert := eq .Values.clientAuth "certificate" -}}
{{- $subj := ternary "PRINCIPAL" "GROUP" $cert -}}
* === Authority records (OAM) — generated by Helm (clientAuth: {{ .Values.clientAuth }}) ===
{{- range .Values.access.platformTeams }}
{{- $id := ternary (.mcUser | default .group) (.group | default .mcUser) $cert }}
{{- include "mqqmgr.authrec.one" (dict "t" . "subj" $subj "id" $id) }}
{{- end }}
{{- range .Values.access.teams }}
{{- $id := ternary (.mcUser | default .group) (.group | default .mcUser) $cert }}
{{- include "mqqmgr.authrec.one" (dict "t" . "subj" $subj "id" $id) }}
{{- end }}
REFRESH SECURITY TYPE(AUTHSERV)
{{- end -}}
